# Generated by Django 3.2.12 on 2022-04-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Рабочий')),
                ('last_name', models.CharField(max_length=200, verbose_name='Рабочий')),
            ],
            options={
                'db_table': 'worker',
            },
        ),
    ]
